Repository pulp/pulp_container, pull requests merged in 2022-08, with the labels that each got.

#945 Get mediaType from the request's content-type
  CHANGES/883.bugfix
  pulp_container/app/tasks/sync_stages.py
  pulp_container/app/utils.py
Labels: backport-2.9

#976 Fixed 404 during sync from registry.redhat.io
  CHANGES/974.bugfix
  pulp_container/app/downloaders.py
Labels: backport-2.10, backport-2.9, backport-2.8, backport-2.11, backport-2.12, backport-2.13

#1003 Add a repair command for fixing media types of v1 manifests
  CHANGES/977.bugfix
  pulp_container/app/management/__init__.py
  pulp_container/app/management/commands/__init__.py
  pulp_container/app/management/commands/container-repair-media-type.py
  pulp_container/app/migrations/0033_raise_warning_for_repair.py
  pulp_container/app/utils.py
Labels: backport-2.13

#1007 Add a repair command for fixing media types of v1 manifests
  CHANGES/977.bugfix
  pulp_container/app/management/__init__.py
  pulp_container/app/management/commands/__init__.py
  pulp_container/app/management/commands/container-repair-media-type.py
  pulp_container/app/utils.py
Labels: backport-2.9
