Repository pulp/pulp_container, pull requests merged in 2024-10, with the labels that each got.

#1687 Add repository_version param as a building context
  CHANGES/479.feature
  docs/admin/guides/build-image.md
  pulp_container/app/serializers.py
  pulp_container/app/tasks/__init__.py
  pulp_container/app/tasks/builder.py
  pulp_container/app/viewsets.py
  pulp_container/tests/functional/api/test_build_images.py
Labels: no-changelog

#1795 Fix item list indentation in docs
  docs/admin/guides/build-image.md
Labels: no-issue, no-changelog

#1797 Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulp_container/app/fields.py
  pulp_container/app/serializers.py
Labels: backport-2.14, backport-2.15, backport-2.16, backport-2.21, backport-2.20, no-issue

#1798 Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulp_container/app/fields.py
  pulp_container/app/serializers.py
Labels: no-issue

#1799 Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulp_container/app/fields.py
  pulp_container/app/serializers.py
Labels: no-issue
