Repository pulp/pulp_container, pull requests merged in 2025-01, with the labels that each got.

#1875 Remove jwk as a required manifest schema parameter
  CHANGES/1874.bugfix
  pulp_container/app/json_schemas.py
Labels: backport-2.15, backport-2.20, backport-2.22, backport-2.19

#1882 Finish CHANGES.md migrations to fix release CI
  CHANGES.md
  CHANGES.rst
  MANIFEST.in
  docs/changes.rst
  pyproject.toml
Labels: no-issue, no-changelog

#1889 Django storages config deprecation (1/2)
  pulp_container/app/registry.py
  pulp_container/app/registry_api.py
  pulp_container/app/tasks/sign.py
Labels: no-issue, no-changelog

#1899 Fix 500 error when using flatpak with reclaimed content [PULP-262]
  CHANGES/1887.bugfix
  pulp_container/app/registry_api.py
  pulp_container/tests/functional/api/test_flatpak.py
  pulp_container/tests/functional/conftest.py
Labels: backport-2.22
